version: "3.8"
    
services:
    zookeeper:
        image: bitnami/zookeeper:latest
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka:latest
        ports:
            - 9092:9092
            - 9093:9093
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
        depends_on:
            - zookeeper

    producer:
        build:
            context: ./kafka_app/producer
            dockerfile: Dockerfile
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        ports:
            - 8080:8000
        volumes:
            - ./kafka_app/producer:/usr/src/app
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_PORT=9092
        depends_on:
            - kafka
            - zookeeper

    consumer:
        build:
            context: ./kafka_app/consumer
            dockerfile: Dockerfile
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./kafka_app/consumer:/usr/src/app
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_PORT=9092
            - KAFKA_TOPICS=jobs
        depends_on:
            - kafka
            - zookeeper